name: Health Checker

on:
  push:
    branches: [main, development]
jobs:
  url_health_check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Url
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-crimson-violet-4961.fly.dev/
          max-attempts: 2
          retry-delay: 5s
